apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rkrvq39r8-java-quarkus
  janus-idp.io/tekton: rkrvq39r8-java-quarkus
  backstage.io/kubernetes-id: rkrvq39r8-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rkrvq39r8-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
